const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='appu90_v4';
const todayISO=()=>new Date().toISOString().slice(0,10);
const niceDate=d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const startDate=localStorage.getItem('appu90_start')||todayISO(); localStorage.setItem('appu90_start',startDate);
const dayNum=Math.min(90,Math.max(1,Math.floor((new Date(todayISO())-new Date(startDate))/(86400000))+1));
const defaults={
 habits:[['SRF Energization','Spiritual'],['Meditation','Spiritual'],['Prayer','Spiritual'],['Protein Target','Health'],['Water Target','Health'],['Movement','Health'],['Sleep Before 10:30 PM','Health'],['Gayathri Program','Growth'],['Goal Journal','Growth'],['Night Goal Script','Growth'],['Daily Money Check','Money']],
 entries:{}, weekly:{},
 schedule:{Monday:['Workout A'],Tuesday:['1 hour feature film writing','30 min job search'],Wednesday:['Workout B','Visibility create'],Thursday:['1 hour feature film writing','30 min job search'],Friday:['Workout C','Visibility review'],Saturday:['1 hour feature film writing'],Sunday:['Recovery Yoga','Full body oil massage','Visibility post','Weekly review']},
 affirmations:['Health is the Main Quest. Everything else is a side quest.','My progress comes from returning, not perfection.','God walks beside me as I heal.','I trust myself to come back.','Recovery counts.','I allow myself to be seen before I feel ready.']
};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||defaults; const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function entry(d=todayISO()){state.entries[d] ||= {checked:{},health:{protein:0,water:0,steps:0,sleep:0,bp:'',wrist:0,mood:'Calm',energy:5},journal:'',gratitude:'',workoutType:'Rest / Recovery',workoutNotes:''}; return state.entries[d];}
function initHeader(){ $('#todayDate').textContent=niceDate(todayISO()); $('#dayNumber').textContent=dayNum; $('#affirmation').textContent=state.affirmations[dayNum%state.affirmations.length];}
function render(tab='today'){ $$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); const tpl=$(`#${tab}-template`); $('#view').innerHTML=''; $('#view').append(tpl.content.cloneNode(true)); ({today,log,habits,health,schedule,report}[tab])(); window.scrollTo({top:0,behavior:'smooth'});}
function today(){ const e=entry(); const list=$('#habitList'); list.innerHTML=''; state.habits.forEach((h,i)=>{let row=document.createElement('label'); row.className='habit-item'; row.innerHTML=`<input type="checkbox" ${e.checked[i]?'checked':''}><div class="habit-meta"><div class="habit-title">${h[0]}</div><div class="habit-cat">${h[1]}</div></div>`; row.querySelector('input').onchange=ev=>{e.checked[i]=ev.target.checked;save();today()}; list.append(row);}); const done=Object.values(e.checked).filter(Boolean).length; $('#doneCount').textContent=done; $('#totalCount').textContent=state.habits.length; $('#dailyProgress').style.width=(state.habits.length?done/state.habits.length*100:0)+'%'; const h=e.health; $('#healthQuick').innerHTML=`<div class="metric-grid"><div class="metric-card"><label>Protein</label><input type="number" data-health="protein" value="${h.protein}"><small>/ 90g</small></div><div class="metric-card"><label>Water</label><input type="number" step="0.1" data-health="water" value="${h.water}"><small>/ 3L</small></div><div class="metric-card"><label>Steps</label><input type="number" data-health="steps" value="${h.steps}"><small>/ 7000</small></div><div class="metric-card"><label>Sleep</label><input type="number" step="0.5" data-health="sleep" value="${h.sleep}"><small>/ 8 hours</small></div></div>`; $$('[data-health]').forEach(inp=>inp.oninput=()=>{e.health[inp.dataset.health]=inp.value;save()}); $('#dailyJournal').value=e.journal; $('#dailyGratitude').value=e.gratitude; $('#dailyJournal').oninput=ev=>{e.journal=ev.target.value;save()}; $('#dailyGratitude').oninput=ev=>{e.gratitude=ev.target.value;save()};}
function habits(){ const ed=$('#habitEditor'); const draw=()=>{ed.innerHTML='';state.habits.forEach((h,i)=>{const row=document.createElement('div'); row.className='editor-item'; row.innerHTML=`<input value="${h[0]}"><select><option>Spiritual</option><option>Health</option><option>Growth</option><option>Money</option><option>Custom</option></select><button class="danger">Delete</button>`; row.querySelector('select').value=h[1]; row.querySelector('input').oninput=e=>{state.habits[i][0]=e.target.value;save()}; row.querySelector('select').onchange=e=>{state.habits[i][1]=e.target.value;save()}; row.querySelector('button').onclick=()=>{state.habits.splice(i,1);save();draw()}; ed.append(row);});}; $('#addHabit').onclick=()=>{const v=$('#newHabit').value.trim(); if(!v)return; state.habits.push([v,$('#newCategory').value]); $('#newHabit').value=''; save(); draw();}; draw();}
function health(){ const e=entry(); const h=e.health; $('#healthForm').innerHTML=[['protein','Protein','90g'],['water','Water','3L'],['steps','Steps','7000'],['sleep','Sleep','8 hours'],['bp','Blood Pressure','simple entry'],['wrist','Wrist Pain','0-10'],['mood','Mood',''],['energy','Energy','0-10']].map(([k,l,t])=>`<div class="metric-card"><label>${l}</label><input ${k==='mood'?'':'type="'+(k==='bp'?'text':'number')+'"'} ${k==='wrist'||k==='energy'?'min="0" max="10"':''} data-k="${k}" value="${h[k]||''}"><small>${t}</small></div>`).join(''); $$('[data-k]').forEach(inp=>inp.oninput=()=>{h[inp.dataset.k]=inp.value;save()}); $('#workoutType').value=e.workoutType; $('#workoutNotes').value=e.workoutNotes; $('#workoutType').onchange=x=>{e.workoutType=x.target.value;save()}; $('#workoutNotes').oninput=x=>{e.workoutNotes=x.target.value;save()};}
function schedule(){ $('#scheduleList').innerHTML=Object.entries(state.schedule).map(([d,t])=>`<div class="schedule-day"><strong style="min-width:100px">${d}</strong><div>${t.map(x=>`<span class="pill">${x}</span>`).join('')}</div></div>`).join('');}
function log(){ const inp=$('#logDate'); inp.value=todayISO(); inp.onchange=()=>draw(inp.value); draw(inp.value); function draw(d){const e=entry(d); const done=Object.values(e.checked||{}).filter(Boolean).length; $('#logDetail').innerHTML=`<div class="log-card"><h4>${niceDate(d)}</h4><p><strong>Habits:</strong> ${done}/${state.habits.length}</p><p><strong>Health:</strong> Protein ${e.health.protein||0}g, Water ${e.health.water||0}L, Steps ${e.health.steps||0}, Sleep ${e.health.sleep||0}h, BP ${e.health.bp||'-'}, Wrist ${e.health.wrist||0}/10</p><p><strong>Journal:</strong><br>${e.journal||'No journal saved.'}</p><p><strong>Gratitude:</strong><br>${e.gratitude||'No gratitude saved.'}</p><p><strong>Workout:</strong> ${e.workoutType||'-'}<br>${e.workoutNotes||''}</p></div>`;}}
function report(){ const days=[...Array(7)].map((_,i)=>{let d=new Date(); d.setDate(d.getDate()-i); return d.toISOString().slice(0,10)}).reverse(); const entries=days.map(d=>entry(d)); const avg=(arr)=>Math.round(arr.reduce((a,b)=>a+Number(b||0),0)/arr.length); const habitsDone=entries.reduce((a,e)=>a+Object.values(e.checked||{}).filter(Boolean).length,0); const total=entries.length*state.habits.length; $('#weekTitle').textContent=`${niceDate(days[0]).split(',')[0]} → ${niceDate(days[6]).split(',')[0]}`; $('#weeklyStats').innerHTML=`<div class="metric-card"><label>Habit completion</label><strong>${total?Math.round(habitsDone/total*100):0}%</strong></div><div class="metric-card"><label>Avg protein</label><strong>${avg(entries.map(e=>e.health.protein))}g</strong></div><div class="metric-card"><label>Avg water</label><strong>${avg(entries.map(e=>e.health.water))}L</strong></div><div class="metric-card"><label>Avg sleep</label><strong>${avg(entries.map(e=>e.health.sleep))}h</strong></div>`; const wk='week-'+Math.ceil(dayNum/7); state.weekly[wk] ||= {worked:'',improve:''}; $('#weeklyWorked').value=state.weekly[wk].worked; $('#weeklyImprove').value=state.weekly[wk].improve; $('#weeklyWorked').oninput=e=>{state.weekly[wk].worked=e.target.value;save()}; $('#weeklyImprove').oninput=e=>{state.weekly[wk].improve=e.target.value;save()};}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>render(b.dataset.tab)); initHeader(); render('today');
if('serviceWorker' in navigator){/* optional later */}
