const TARGETS={protein:90,water:3,steps:7000,sleep:8};
const START_KEY='lifeProgramStartDate';
const todayISO=()=>new Date().toISOString().slice(0,10);
const storeKey=(name)=>`life90:${todayISO()}:${name}`;
const $=(id)=>document.getElementById(id);
const habits=['SRF Energization','Meditation','Prayer','Protein Target','Water Target','Movement','Sleep Before 10:30 PM','Gayathri Program 30 mins','Goal Journal','Night Goal Script','Daily Reflection'];
const affirmations=['I am becoming a man who takes care of the body God entrusted to him.','My progress comes from returning, not perfection.','I trust myself to come back.','God walks beside me as I heal.','I love myself for who I am.','Health is my main quest. Everything else is a side quest.','I trust myself to bounce back.','I allow myself to be seen before I feel ready.','I trust myself to make responsible financial decisions.','I am creating financial stability one decision at a time.'];
const schedule={
  Monday:['Workout A','Build strength safely'], Tuesday:['30 min job search','1 hour feature film writing'], Wednesday:['Workout B','Create weekly visibility content'], Thursday:['30 min job search','1 hour feature film writing'], Friday:['Workout C','Review weekly content'], Saturday:['1 hour feature film writing','Stay with the story'], Sunday:['Recovery Yoga','Full body oil massage','Post weekly content','Weekly review']
};
function initStart(){if(!localStorage.getItem(START_KEY))localStorage.setItem(START_KEY,todayISO());}
function dayNum(){const start=new Date(localStorage.getItem(START_KEY));const now=new Date(todayISO());return Math.min(90,Math.max(1,Math.floor((now-start)/86400000)+1));}
function toast(msg='Saved'){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
function save(name,val){localStorage.setItem(storeKey(name),JSON.stringify(val));}
function load(name,fallback=null){const v=localStorage.getItem(storeKey(name));return v?JSON.parse(v):fallback;}
function renderRing(){const d=dayNum();$('dayNumber').textContent=d;const pct=d/90;const c=327;$('ringProgress').style.strokeDashoffset=c-(c*pct);}
function renderAffirmation(){const index=Math.floor(Date.now()/1000/60/60)%affirmations.length;$('affirmationText').textContent=affirmations[index];}
function renderHabits(){const saved=load('habits',{});const wrap=$('habitList');wrap.innerHTML='';habits.forEach(h=>{const label=document.createElement('label');label.className='check-item';label.innerHTML=`<input type="checkbox" ${saved[h]?'checked':''}><span>${h}</span>`;label.querySelector('input').addEventListener('change',e=>{saved[h]=e.target.checked;save('habits',saved);renderFoundationScore();});wrap.appendChild(label);});renderFoundationScore();}
function renderFoundationScore(){const saved=load('habits',{});const count=habits.filter(h=>saved[h]).length;$('foundationScore').textContent=`${count}/${habits.length}`;}
function renderTodayTasks(){const name=new Date().toLocaleDateString('en-GB',{weekday:'long'});$('todayName').textContent=name;const tasks=schedule[name]||[];$('todayTasks').innerHTML=tasks.map((t,i)=>`<div class="focus-item"><span>${t}</span><b>${i===0?'Main':'Side'}</b></div>`).join('');}
function renderHealth(){['protein','water','steps','sleep','bp','mood','energy','wrist'].forEach(id=>{const el=$(id);const v=load(id,'');el.value=v;el.addEventListener('input',()=>{save(id,el.value);renderBars();});});$('saveHealth').onclick=()=>toast('Health check-in saved');renderBars();}
function renderBars(){const vals={protein:+($('protein').value||0),water:+($('water').value||0),steps:+($('steps').value||0),sleep:+($('sleep').value||0)};const entries=Object.entries(TARGETS);let total=0;$('healthBars').innerHTML=entries.map(([k,t])=>{const pct=Math.min(100,Math.round((vals[k]/t)*100)||0);total+=pct;return `<div class="bar-row"><div class="bar-meta"><span>${k[0].toUpperCase()+k.slice(1)}</span><span>${pct}%</span></div><div class="bar"><span style="width:${pct}%"></span></div></div>`}).join('');$('healthPercent').textContent=`${Math.round(total/entries.length)}%`;}
function renderVisibility(){const week=Math.ceil(dayNum()/7);const currentBlock=Math.ceil(week/4);let cards='';for(let i=1;i<=4;i++){const w=(currentBlock-1)*4+i;if(w>13)break;const even=w%2===0;cards+=`<div class="vis-card ${w===week?'active':''}"><h3>Week ${w}</h3><p>${even?'Face / voice required':'Image or text allowed'}</p></div>`;}$('visibilityWeek').innerHTML=cards;['created','reviewed','posted'].forEach(id=>{const el=$(id);el.checked=!!load(id,false);el.onchange=()=>save(id,el.checked);});}
function renderMoneyReview(){$('moneyCheck').value=load('moneyCheck','');$('saveMoney').onclick=()=>{save('moneyCheck',$('moneyCheck').value);toast('Money check saved')};['scoreHealth','scoreCreativity','scoreVisibility','scoreMoney','scoreSpirituality','weeklyReflection'].forEach(id=>{const el=$(id);el.value=load(id,'');el.addEventListener('input',()=>save(id,el.value));});$('saveReview').onclick=()=>toast('Weekly review saved');}
function tabs(){document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab,.panel').forEach(el=>el.classList.remove('active'));btn.classList.add('active');$(btn.dataset.tab).classList.add('active');}));}
initStart();renderRing();renderAffirmation();renderHabits();renderTodayTasks();renderHealth();renderVisibility();renderMoneyReview();tabs();
